services:
  - type: web
    name: sauna-dashboard
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd frontend && npm install && npm run build && cd ..
      mkdir -p static
      [ -d frontend/build/static ] && cp -r frontend/build/static/* static/
      [ -f frontend/build/index.html ] && cp frontend/build/index.html static/
    startCommand: RENDER=true python server.py
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: true
    healthCheckPath: /
    autoDeploy: true
